listener 1883
allow_anonymous true
persistence false
log_type error
log_type warning

connection bridge-from-sbc1
address 192.168.1.100:1883
topic facility/zone1/alerts in 0
restart_timeout 5

connection bridge-from-sbc2
address 192.168.1.101:1883
topic facility/zone2/alerts in 0
restart_timeout 5
